# Generated by Django 6.0 on 2025-12-25 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowpayments_invoice_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nowpayments_payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('sending', 'Sending'), ('partially_paid', 'Partially Paid'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], db_index=True, default='waiting', max_length=20)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(default='usd', max_length=10)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('pay_currency', models.CharField(blank=True, max_length=10)),
                ('actually_paid', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('invoice_url', models.URLField(max_length=500)),
                ('webhook_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nowpayments_invoice_id'], name='payments_pa_nowpaym_7b59bb_idx'), models.Index(fields=['nowpayments_payment_id'], name='payments_pa_nowpaym_ac4ca9_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['-created_at'], name='payments_pa_created_3147e3_idx')],
            },
        ),
    ]
